### ISSUE TITLE
react router V4

### ISSUE THREAD

**Issue by songguangyu** [hyy1115/react-next#1]
Hello，我看到这个项目 感觉非常好，但是我看了下发现并没有使用react router v4。请问有使用react router v4 服务端渲染的demo吗？ 十分感谢。

**Comment by hyy1115** [comment]
next框架自带next-routes路由插件，如果要把它改成react-router，你可以去问问next-routes的开发者能不能支持：https://github.com/fridays/next-routes/issues

**Comment by songguangyu** [comment]
嗯 我之前一直用的 router1.0 react 0.15 最近正往高版本弄 做一些同构方案，Next.js 看了看这个 感觉有些不太适合我们。 看了看react router 服务端渲染的文档，发现写的太简单了。感谢
