### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Banlangenn** [hyy1115/react-next#2]
npm build   npm  start   

 报错  
   react-next@1.0.0 start C:\Users\liujiwei\Desktop\新闻内容react\react-next
> NODE_ENV=production  start server.js

'NODE_ENV' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-next@1.0.0 start: `NODE_ENV=production  start server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-next@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\liujiwei\AppData\Roaming\npm-cache\_logs\2018-01-15T07_12_32_918Z-debug.log

**Comment by hyy1115** [comment]
我不记得有这样一条指令
```
//error work
NODE_ENV=production start server.js
```
在本地，你应该使用
```
npm run dev
```

**Comment by Banlangenn** [comment]
恩
